#!/usr/bin/env python3
"""
Reads docs/Staff List/UPDATED STAFFLIST 2026 FOR 39.xlsx and generates
packages/api/src/db/migration-officers-staff-id-backfill.sql.

Run from repo root:
  python scripts/gen-staff-reconciliation-migration.py
"""
import re
import sys
from pathlib import Path

try:
    import openpyxl
except ImportError:
    sys.exit("openpyxl not installed — run: pip install openpyxl")

REPO_ROOT = Path(__file__).parent.parent
EXCEL_PATH = REPO_ROOT / "docs" / "Staff List" / "UPDATED STAFFLIST 2026 FOR 39.xlsx"
OUT_PATH = REPO_ROOT / "packages" / "api" / "src" / "db" / "migration-officers-staff-id-backfill.sql"
SHEET_NAME = "Updated stafflist OHCS"


def clean(val) -> str:
    return str(val).strip() if val is not None else ""


def is_numeric_staff_id(val) -> bool:
    if isinstance(val, (int, float)) and val > 0:
        return True
    if isinstance(val, str) and re.match(r"^\d+$", val.strip()):
        return True
    return False


def to_staff_no(val) -> str:
    return str(int(float(str(val).strip())))


def escape_sql(s: str) -> str:
    return s.replace("'", "''")


def main():
    if not EXCEL_PATH.exists():
        sys.exit(f"Excel file not found: {EXCEL_PATH}")

    wb = openpyxl.load_workbook(EXCEL_PATH, read_only=True, data_only=True)
    if SHEET_NAME not in wb.sheetnames:
        sys.exit(f"Sheet '{SHEET_NAME}' not found. Available: {wb.sheetnames}")

    ws = wb[SHEET_NAME]
    rows = list(ws.iter_rows(min_row=3, values_only=True))

    statements: list[str] = []
    skipped: list[str] = []

    for row in rows:
        col_b = row[1]   # Staff No.
        col_c = row[2]   # First Name
        col_d = row[3]   # Surname
        col_r = row[17] if len(row) > 17 else None  # Phone No.

        if not is_numeric_staff_id(col_b):
            continue

        staff_no = to_staff_no(col_b)
        officer_id = f"off_{staff_no}"
        phone = clean(col_r)

        first = clean(col_c)
        surname = clean(col_d)
        # Remove trailing " Male"/"Female" that appears in some surname cells
        surname = re.sub(r"\s+(Male|Female)$", "", surname, flags=re.IGNORECASE).strip()

        if not phone:
            skipped.append(f"  -- staff_no={staff_no} ({first} {surname}): no phone in Excel")

        phone_sql = escape_sql(phone) if phone else ""
        phone_val = f"'{phone_sql}'" if phone else "NULL"

        # Unconditional UPDATE: safe and idempotent (no-op when id doesn't exist).
        # Avoids IS DISTINCT FROM which D1/SQLite does not support.
        statements.append(
            f"UPDATE officers SET staff_id = '{staff_no}', phone = {phone_val} "
            f"WHERE id = '{officer_id}';"
        )

    header = """\
-- Auto-generated by scripts/gen-staff-reconciliation-migration.py — do not edit by hand
-- Backfills officers.staff_id and phone from UPDATED STAFFLIST 2026 FOR 39.xlsx
-- (sheet: "Updated stafflist OHCS", column B = Staff No., column R = Phone)
-- Safe to re-run: UPDATE on a non-existent id is a no-op; existing values are overwritten
-- with the authoritative Excel values.
"""

    footer_lines = []
    if skipped:
        footer_lines.append("\n-- Staff with no phone number in Excel (phone set to NULL):")
        footer_lines.extend(skipped)

    content = header + "\n".join(statements) + "\n" + "\n".join(footer_lines) + "\n"

    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {len(statements)} UPDATE statements to:")
    print(f"  {OUT_PATH}")
    if skipped:
        print(f"  {len(skipped)} staff had no phone in Excel (phone set to NULL — see comments at end of file)")


if __name__ == "__main__":
    main()
